name: temp12k
dependencies:
    - cartopy
    - xarray
    - netcdf4
    - openpyxl
    - xlrd
    - matplotlib
    - ipywidgets
    - ipython
    - notebook
    - appmode
    - ipympl
    - qgrid
    - pip
    - pip:
        - qgrid
